<#
.SYNOPSIS
    Gold Trader MT5 Connector - One-Command Deployment Script for Windows
    
.DESCRIPTION
    This script deploys the MT5 Connector on Windows with MetaTrader 5.
    The connector streams real-time price data to the trading server.

.PARAMETER ServerUrl
    URL of the trading server (default: ws://localhost:8001)

.PARAMETER MT5Path
    Path to MetaTrader 5 terminal (default: C:\Program Files\MetaTrader 5\terminal64.exe)

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File deploy-connector.ps1

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File deploy-connector.ps1 -ServerUrl "ws://192.168.1.100:8001"
#>

param(
    [string]$ServerUrl = "ws://localhost:8001",
    [string]$MT5Path = "C:\Program Files\MetaTrader 5\terminal64.exe",
    [string]$MT5Login = "",
    [string]$MT5Password = "",
    [string]$MT5Server = ""
)

$ErrorActionPreference = "Stop"

# ============================================================================
# COLORS
# ============================================================================
$RED = "Red"
$GREEN = "Green"
$YELLOW = "Yellow"
$BLUE = "Blue"
$CYAN = "Cyan"
$WHITE = "White"

function Write-Colored {
    param([string]$Message, [string]$Color = $WHITE)
    Write-Host $Message -ForegroundColor $Color
}

# ============================================================================
# BANNER
# ============================================================================
Write-Colored "`n╔══════════════════════════════════════════════════════════════════════════════╗" $CYAN
Write-Colored "║              GOLD TRADER MT5 CONNECTOR DEPLOYMENT SCRIPT                      ║" $CYAN
Write-Colored "║                    Windows One-Command Installer                             ║" $CYAN
Write-Colored "╚══════════════════════════════════════════════════════════════════════════════╝`n" $CYAN

# ============================================================================
# STEP 1: Check Python
# ============================================================================
Write-Colored "🐍 Step 1: Checking Python installation..." $BLUE

try {
    $pythonVersion = python --version 2>&1
    if ($LASTEXITCODE -ne 0) {
        # Try py command
        $pythonVersion = py --version 2>&1
    }
    Write-Colored "✅ Python found: $pythonVersion" $GREEN
} catch {
    Write-Colored "❌ Python is not installed or not in PATH" $RED
    Write-Colored "   Please install Python 3.11+ from https://python.org" $YELLOW
    exit 1
}

# ============================================================================
# STEP 2: Install Dependencies
# ============================================================================
Write-Colored "`n📦 Step 2: Installing Python dependencies..." $BLUE

$requirements = @(
    "MetaTrader5>=5.0.45",
    "websockets>=12.0",
    "python-socketio>=5.11.0",
    "aiohttp>=3.9.1",
    "python-dotenv>=1.0.0",
    "pydantic>=2.5.3",
    "pydantic-settings>=2.1.0",
    "structlog>=24.1.0",
    "prometheus-client>=0.19.0"
)

foreach ($pkg in $requirements) {
    Write-Host "  Installing $pkg... " -NoNewline
    try {
        pip install $pkg 2>&1 | Out-Null
        Write-Colored "✅" $GREEN
    } catch {
        Write-Colored "❌" $RED
        Write-Host "   Error: $_" -ForegroundColor $RED
    }
}

# ============================================================================
# STEP 3: Create Connector Directory
# ============================================================================
Write-Colored "`n📁 Step 3: Creating connector directory..." $BLUE

$connectorDir = "C:\GoldTrader\Connector"
if (-not (Test-Path $connectorDir)) {
    New-Item -ItemType Directory -Path $connectorDir -Force | Out-Null
}
Write-Colored "✅ Directory created: $connectorDir" $GREEN

# ============================================================================
# STEP 4: Generate Configuration
# ============================================================================
Write-Colored "`n⚙️  Step 4: Creating configuration..." $BLUE

$mt5Configured = $false
if ($MT5Login -and $MT5Password -and $MT5Server) {
    $mt5Configured = $true
}

$configContent = @"
# Gold Trader MT5 Connector Configuration
# Generated by deploy-connector.ps1

# Server Configuration
SERVER_URL=$ServerUrl
WEBSOCKET_PORT=8001

# MT5 Configuration
MT5_PATH=$MT5Path
MT5_LOGIN=$MT5Login
MT5_PASSWORD=$MT5Password
MT5_SERVER=$MT5Server

# Symbol to trade
SYMBOL=XAUUSD

# Reconnection Settings
RECONNECT_DELAY=5
MAX_RECONNECT_ATTEMPTS=100

# Heartbeat
HEARTBEAT_INTERVAL=30

# Logging
LOG_LEVEL=INFO
LOG_FILE=connector.log
"@

$configContent | Out-File -FilePath "$connectorDir\.env" -Encoding UTF8
Write-Colored "✅ Configuration saved to $connectorDir\.env" $GREEN

# ============================================================================
# STEP 5: Create Connector Script
# ============================================================================
Write-Colored "`n📝 Step 5: Creating connector script..." $BLUE

$connectorScript = @"
#!/usr/bin/env python3
"""
Gold Trader MT5 Connector
Streams real-time XAUUSD price data to the trading server.
"""

import asyncio
import websockets
import json
import logging
import signal
import sys
from pathlib import Path
from datetime import datetime
from decimal import Decimal

# Load environment
from dotenv import load_dotenv
load_dotenv(Path(__file__).parent / '.env')

import MetaTrader5 as mt5


class MT5Connector:
    def __init__(self):
        self.server_url = self.get_env('SERVER_URL', 'ws://localhost:8001')
        self.symbol = self.get_env('SYMBOL', 'XAUUSD')
        self.reconnect_delay = int(self.get_env('RECONNECT_DELAY', '5'))
        self.max_reconnect = int(self.get_env('MAX_RECONNECT_ATTEMPTS', '100'))
        self.heartbeat_interval = int(self.get_env('HEARTBEAT_INTERVAL', '30'))
        
        self.websocket = None
        self.running = False
        self.last_tick = None
        
        # Setup logging
        log_level = self.get_env('LOG_LEVEL', 'INFO')
        logging.basicConfig(
            level=getattr(logging, log_level),
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        )
        self.logger = logging.getLogger('MT5Connector')
        
    def get_env(self, key, default=''):
        import os
        return os.environ.get(key, default)
    
    async def connect_mt5(self):
        self.logger.info(f"Connecting to MT5 for {self.symbol}...")
        
        mt5_path = self.get_env('MT5_PATH', '')
        if mt5_path and Path(mt5_path).exists():
            mt5.initialize(path=mt5_path)
        else:
            mt5.initialize()
        
        # Login if credentials provided
        login = self.get_env('MT5_LOGIN', '')
        password = self.get_env('MT5_PASSWORD', '')
        server = self.get_env('MT5_SERVER', '')
        
        if login and password and server:
            if mt5.login(login, password, server):
                self.logger.info(f"MT5 connected and logged in")
            else:
                self.logger.warning(f"MT5 login failed: {mt5.last_error()}")
        else:
            self.logger.info("MT5 connected (no credentials provided)")
        
        # Subscribe to symbol
        if mt5.symbol_select(self.symbol, True):
            self.logger.info(f"Subscribed to {self.symbol}")
        else:
            self.logger.error(f"Failed to subscribe to {self.symbol}")
            
    async def connect_server(self):
        self.logger.info(f"Connecting to server: {self.server_url}")
        self.websocket = await websockets.connect(
            self.server_url,
            ping_interval=self.heartbeat_interval,
            ping_timeout=10
        )
        self.logger.info("Connected to server")
        
    async def send_tick(self, tick):
        if self.websocket:
            message = {
                'type': 'tick',
                'symbol': self.symbol,
                'timestamp': datetime.utcnow().isoformat() + 'Z',
                'bid': float(tick.bid),
                'ask': float(tick.ask),
                'last': float(tick.last) if tick.last else float(tick.bid),
                'volume': tick.volume
            }
            try:
                await self.websocket.send(json.dumps(message))
            except Exception as e:
                self.logger.error(f"Failed to send tick: {e}")
                
    async def handle_messages(self):
        async for message in self.websocket:
            data = json.loads(message)
            if data.get('type') == 'ping':
                await self.websocket.send(json.dumps({'type': 'pong'}))
            elif data.get('type') == 'subscribe':
                self.logger.info(f"Subscription received: {data}")
                
    async def run(self):
        self.running = True
        reconnect_count = 0
        
        while self.running and reconnect_count < self.max_reconnect:
            try:
                await self.connect_mt5()
                await self.connect_server()
                reconnect_count = 0
                
                # Send initial tick
                tick = mt5.symbol_info_tick(self.symbol)
                if tick:
                    await self.send_tick(tick)
                
                # Main loop
                while self.running:
                    try:
                        # Get latest tick
                        tick = mt5.symbol_info_tick(self.symbol)
                        if tick and tick.bid != self.last_tick:
                            self.last_tick = tick.bid
                            await self.send_tick(tick)
                        
                        # Handle server messages
                        await asyncio.wait_for(self.handle_messages(), timeout=1.0)
                        
                    except asyncio.TimeoutError:
                        continue
                    except Exception as e:
                        self.logger.error(f"Error in main loop: {e}")
                        break
                        
            except Exception as e:
                self.logger.error(f"Connection error: {e}")
                reconnect_count += 1
                if reconnect_count < self.max_reconnect:
                    self.logger.info(f"Reconnecting in {self.reconnect_delay}s... (attempt {reconnect_count})")
                    await asyncio.sleep(self.reconnect_delay)
                else:
                    self.logger.error("Max reconnection attempts reached")
                    
    def stop(self):
        self.running = False
        if mt5.initialized():
            mt5.shutdown()
        self.logger.info("Connector stopped")


async def main():
    connector = MT5Connector()
    
    # Setup signal handlers
    loop = asyncio.get_event_loop()
    
    def signal_handler():
        connector.stop()
        sys.exit(0)
    
    loop.add_signal_handler(signal.SIGINT, signal_handler)
    loop.add_signal_handler(signal.SIGTERM, signal_handler)
    
    try:
        await connector.run()
    except KeyboardInterrupt:
        connector.stop()


if __name__ == "__main__":
    asyncio.run(main())
"@

$connectorScript | Out-File -FilePath "$connectorDir\connector.py" -Encoding UTF8
Write-Colored "✅ Connector script created" $GREEN

# ============================================================================
# STEP 6: Create Launcher Script
# ============================================================================
Write-Colored "`n🚀 Step 6: Creating launcher script..." $BLUE

$launcherScript = @"
@echo off
REM Gold Trader MT5 Connector Launcher
REM Run this script to start the connector

echo Starting Gold Trader MT5 Connector...
cd /d "%~dp0"
python connector.py
pause
"@

$launcherScript | Out-File -FilePath "$connectorDir\run-connector.bat" -Encoding ASCII
Write-Colored "✅ Launcher script created (run-connector.bat)" $GREEN

# ============================================================================
# STEP 7: Summary
# ============================================================================
Write-Colored "`n" $CYAN
Write-Colored "╔══════════════════════════════════════════════════════════════════════════════╗" $CYAN
Write-Colored "║                    DEPLOYMENT COMPLETE! 🎉                                    ║" $CYAN
Write-Colored "╚══════════════════════════════════════════════════════════════════════════════╝" $CYAN

Write-Colored "`n📍 CONNECTOR LOCATION: $connectorDir" $GREEN
Write-Colored "`n📋 FILES CREATED:" $GREEN
Write-Host "   - connector.py     (Main connector script)"
Write-Host "   - run-connector.bat (Launcher script)"
Write-Host "   - .env             (Configuration)"

Write-Colored "`n🚀 TO START THE CONNECTOR:" $YELLOW
Write-Host "   Option 1: Double-click: $connectorDir\run-connector.bat"
Write-Host "   Option 2: Run: python $connectorDir\connector.py"

Write-Colored "`n⚙️  CONFIGURATION:" $YELLOW
Write-Host "   Server URL: $ServerUrl"
Write-Host "   MT5 Path:   $MT5Path"
if ($mt5Configured) {
    Write-Host "   MT5 Login:  $MT5Login"
    Write-Host "   MT5 Server: $MT5Server"
} else {
    Write-Host "   MT5 Login:  NOT CONFIGURED - Will use current MT5 session"
}

Write-Colored "`n📝 NOTES:" $YELLOW
Write-Host "   - Ensure MetaTrader 5 is installed and running"
Write-Host "   - Ensure the trading server is running (Linux deployment)"
Write-Host "   - The connector will automatically connect and stream data"

Write-Colored "`n✅ Connector is ready to use!" $GREEN
Write-Host ""
